#!/bin/bash

# The Fully Qualified URL of the EventGrid Function.
# e.g. http://localhost:7071/runtime/webhooks/eventgrid?functionName=EventGridTrigger
AZ_EGF_URL="http://localhost:7071/runtime/webhooks/eventgrid?functionName=EventGridTrigger"

# OUTPUT FORMATTING
HEADER='\033[0;32m'
WARNING='\033[0;31m'
NC='\033[0m'

# Validate the input
if [ -z "$AZ_EGF_URL" ]; then
  echo -e "\n${WARNING}Variable AZ_EGF_URL must have a value.${NC}\n"
  exit
fi

echo -e "\n${HEADER}Sending EventGrid Event.${NC}"
curl -X POST "$AZ_EGF_URL" -H 'Content-Type: application/json' -H 'aeg-event-type: Notification' -d'
{
  "id":"b6ee0afd-d594-4d3a-989f-a2837e215e3f",
  "subject":"/demo/Event/3e44747e58c62c38f20ad70f22e26177",
  "eventType":"Event.created",
  "data": {
    "batchId":"",
    "agentId":"training@wellline.com"
  },
  "eventTime":"2019-09-16T15:11:49.058Z",
  "dataVersion":"1.0",
  "metadataVersion":"1",
  "topic":"/subscriptions/XXXXXXX/resourceGroups/YYYYYYYY/providers/Microsoft.EventGrid/topics/ZZZZZZ"
}
'


