#!/bin/bash

# (C) 2019 Maana, Inc.

# OUTPUT FORMATTING
HEADER='\033[0;32m'
WARNING='\033[0;31m'
NC='\033[0m'

# CONFIGURATION PARAMETERS
# Need to replace the following placeholders:
# <ADFS_URL> = ADFS Server URL you are authenticating against.
# <ADFS_APP_ID> = ADFS Application ID you are authenticating against.

# AUTH_URL="<ADFS_URL>/adfs/oauth2/token"
AUTH_URL="https://fs.training.wellline.com/adfs/oauth2/token"

# CLIENT_ID="<ADFS_APP_ID"
CLIENT_ID="wellline_app"

# THESE COME FROM THE USER AT RUNTIME
USER_ID=""
PASSWORD=""

usage()
{
    echo "usage: getAdfsAuthToken [[[-u userid ] [-p password]] | [-h]]"
}

while [ "$1" != "" ]; do
    case $1 in
        -u | --userid )     shift
                            USER_ID=$1
                            ;;
        -p | --password )   shift
                            PASSWORD=$1
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

# Validate the input
if [ -z "$USER_ID" ]; then
  read -p "User ID: " USER_ID
fi
if [ -z "$PASSWORD" ]; then
  read -s -p "Password: " PASSWORD
  echo
fi

echo -e "\n${HEADER}Getting TimeLine Service authentication token for $USER_ID ....${NC}\n"

curl -X POST $AUTH_URL \
 -H 'Accept: application/json' \
 -H 'Content-Type: application/x-www-form-urlencoded' \
 -H 'cache-control: no-cache' \
 -d "grant_type=password&client_id=$CLIENT_ID&scope=openid&response_mode=form_post&username=$USER_ID&password=$PASSWORD"
